version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:<< parameters.python-version >>
    steps:
      - run: locale-gen "en_US.UTF-8"; update-locale LC_ALL="en_US.UTF-8"
      - checkout
      - run: pip3 install --upgrade pip
      - run: pip3 install -r requirements.txt
      - run: pytest

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              python-version: ["3.5", "3.6", "3.7", "3.8", "3.9"]
