version: 2.1

jobs:
  test:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>
    steps:
      - checkout
      - run: pip3 install --upgrade pip
      - run: if python3 --version | grep -q "Python 3.6"; then pip install --prefer-binary -U opencv-python-headless numpy; fi  # to avoid compilation
      - run: pip3 install -r requirements.txt
      - run: pip3 install pytest
      - run: pytest

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
